version: '3'

services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 app:app

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"  # Только HTTP порт
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/app/static
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    restart: always 